name: windows-x64-cpu-vs2019
on: [push, pull_request]
env:
  GO111MODULE: on
  # For versions earlier than Go 1.13
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  windows-vs2019-sse2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # - name: vcpkgtest1
      #   shell: cmd
      #   run: |
      #     git clone https://github.com/microsoft/vcpkg
      #     cmd /c .\vcpkg\bootstrap-vcpkg.bat
      #     dir /s *.exe
      #     .\vcpkg\vcpkg.exe install spdlog

      - name: configure
        run: |
          mkdir build; cd build
          cmake ..
      - name: build
        run: cmake --build build --config Release
    #- name: test
    #  run: cd ./cplussharp/vscode/test ; cd build; ctest -C Release --output-on-failure -j 2
